apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: todo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo-pod
      app: todo-app
  template:
    metadata:
      name: mongo-pod
      labels:
        name: mongo-pod
        app: todo-app
    spec:
      containers:
        - name: mongo
          image: mongo
          # env:
          #   - name: MONGO_INITDB_ROOT_USERNAME
          #     value: root
          #   - name: MONGO_INITDB_ROOT_PASSWORD
          #     value: example
          ports:
            - containerPort: 27017