---
- hosts: master
  become: yes
  vars:
    user: ansible_user
  tasks:
    # - name: initialize the cluster
    #   become: yes
    #   shell: kubeadm init


    - name: create .kube directory
      become: yes
      file:
        path: $HOME/.kube
        state: directory
        directory: present

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes

    - name: change owner for kube config
      file:
        path: $HOME/.kube/config
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Install weavenet pod network
      become: false
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"