---
- hosts: master
  become: yes
  vars:
    user: ansible_user
  tasks:
    - name: initialize the cluster
      become: yes
      shell: kubeadm init


    - name: create .kube directory
      become: yes
      become_user: "{{ user }}"
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        become: true
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: Install weavenet pod network
      become: false
      shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"