---
- hosts: master_node
  become: true
  vars:
    user: ansible_user
  tasks:
    - name: Add an apt signing key for Kubernetes
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Adding apt repository for Kubernetes
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present
        filename: kubernetes.list

    - name: Install Kubernetes binaries
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
      vars:
        packages:
          - kubelet
          - kubeadm
          - kubectl

    # - name: Restart kubelet
    #   service:
    #     name: kubelet
    #     daemon_reload: yes
    #     state: restarted

    - name: Run kubeadm init
      become: true
      command: "kubeadm init"

    - name: Setup kubeconfig for ansible_user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/"{{ user }}"/.kube
        - cp -i /etc/kubernetes/admin.conf /home/"{{ user }}"/.kube/config
        - chown "{{ user }}":"{{ user }}" $HOME/.kube/config

    - name: Install weavenet pod network
      become: false
      command: <<EOTkubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"EOT

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

    - name: Get nodes
      command: "kubectl get nodes"